// <auto-generated />
namespace a12206149_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mvc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mvc));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100713411_mvc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
